# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.define "gateway" do |gateway|
    gateway.vm.hostname = "gateway"
    gateway.vm.provider "virtualbox" do |vb|
    vb.name = "gateway"
    vb.cpus = 2
    vb.memory = 2048
    end
    gateway.vm.network "public_network"
    gateway.vm.network "private_network", ip: "192.168.33.254"

    gateway.vm.provision "shell", inline: <<-SCRIPT
      sudo ip route del default via 10.0.2.2 dev enp0s3
    SCRIPT
  end

  config.vm.define "web-server1" do |web-server1|
    web-server1.vm.hostname = "web-server1"
    web-server1.vm.provider "virtualbox" do |vb|
    vb.name = "web-server1"
    vb.cpus = 2
    vb.memory = 2048
    end
    web-server1.vm.network "private_network", ip: "192.168.33.10"

    web-server1.vm.provision "shell", inline: <<-SCRIPT
      sudo ip route del default via 10.0.2.2 dev enp0s3
      sudo apt-get update
      sudo apt-get install -y nginx
    SCRIPT
  end

  config.vm.define "web-server2" do |web-server2|
    web-server2.vm.hostname = "web-server2"
    web-server2.vm.provider "virtualbox" do |vb|
    vb.name = "web-server2"
    vb.cpus = 2
    vb.memory = 2048
    end
    web-server2.vm.network "private_network", ip: "192.168.33.20"

    web-server2.vm.provision "shell", inline: <<-SCRIPT
      sudo ip route del default via 10.0.2.2 dev enp0s3
      sudo apt-get update
      sudo apt-get install -y nginx
    SCRIPT
  end
end
