# nfs-vol.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-vol
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  volumeName: nfs-pv
  storageClassName: ""
---
# nfs-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.1
  nfs:
    path: /mnt/nfs_share1
    server: 192.168.10.14
