apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: mypod
    version: "1"
    date: "2023-07-25"
    year: "2023"
    month: "07"
    day: "25"
spec:
  containers:
  - name: web-nginx
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  imagePullSecrets:
  - name: docker-pull-secret