apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
data:
  fluent-bit.conf: |
    [INPUT]
        Name          tail
        Path          /fluent-bit/log/access.log, /fluent-bit/log/error.log

    [OUTPUT]
        Name          syslog
        Match         *
        Host          <rsyslog-server-ip>
        Port          514
        Mode          tcp
        Syslog_Format rfc3164
