apiVersion: v1
kind: Secret
metadata:
  name: nginx-ssl-tls-secret
type: Opaque
data:
  localhost.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZzVENDQTVtZ0F3SUJBZ0lVY2xBaFErRXU1
    c3NpYytrYUd5NGhZOHcxNXEwd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2FERUxNQWtHQTFVRUJoTUNT
    MUl4RGpBTUJnTlZCQWdNQlV0dmNtVmhNUTR3REFZRFZRUUhEQVZDZFhOaApiakVTTUJBR0ExVUVD
    Z3dKYlhsamIyMXdZVzU1TVJFd0R3WURWUVFMREFodmNHVnlZWFJ2Y2pFU01CQUdBMVVFCkF3d0pi
    RzlqWVd4b2IzTjBNQjRYRFRJek1EZ3dNekEwTXpjME9Wb1hEVEkwTURnd01qQTBNemMwT1Zvd2FE
    RUwKTUFrR0ExVUVCaE1DUzFJeERqQU1CZ05WQkFnTUJVdHZjbVZoTVE0d0RBWURWUVFIREFWQ2RY
    TmhiakVTTUJBRwpBMVVFQ2d3SmJYbGpiMjF3WVc1NU1SRXdEd1lEVlFRTERBaHZjR1Z5WVhSdmNq
    RVNNQkFHQTFVRUF3d0piRzlqCllXeG9iM04wTUlJQ0lqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0Fn
    OEFNSUlDQ2dLQ0FnRUFzTWU5Wit4YkxERFIKSEtxNzZxN1VudTQ3L2FwOWdrVU52Z2l5M1JjQmR1
    QmZwdFdRU0hzbGtkZFZmeFFUNzZ1RVJkS2NFVXJYY3BIUQpVSUY5aHlEempzTWFOdWNzMmVxdzU0
    ZmN4UC9yS1B5d3dhNXRNUHEvQ1RnaVdMRWhPT0hTZkFRRXlsV3ArdzBXClByMkRnWnBwaC9EaXFI
    cTBrRFVBOUdLT21jdjE5UGVNRTlEOVczekliUk1Nb3RBbzdjN0poaWN4b24wZStjWVoKeWlsc1VY
    RGVkRGNLd2xlL0xOcHNLU0VUN3Z0RWVyMDgwOEtwQkJHb3ltWG4rMUs1bEZpWFA5OFBJcVFyTEN2
    YQpZdGdSclFaNGxXNVFJK0huYng4amJzYkJ0T0dOdzIvOTdpck9STWl4Y1hQNm1DQnpNZ2dVbjg5
    TmNaVDlpQ2JmCjUvNzFiaWtVckJRN1dYbXM2c3BLb0JCSUw4MHVxOWd0NnNIM0NYL0NWZW5sQnhi
    WVovRExsT0t0STJ6eVRld1EKSStvWHpDdmZZMTBqc3M3ay9pR0dNa2NBYmVLUzZzSzhpRU8zMWNN
    NDA2Vnk5TURYL1pIUkdEQzdSWnBVUXY3VQo3WmhmdXl6V3F3V2FoSlVFVWRwZmFwanVOR3J4SjlL
    Z1BYQ1dIcjgvQ09SRW5TL2pZYm91NWtONElwa3hkQk5BCmxydVJVenR0aEpLRFIvdUVqRDZsSVd6
    ZWFmWXg1dkhidFBwd2hHcVhUdUowZUNscTQ4SGMwbnVuLytiNG9VajcKc3ZVU0VYcGhsNExETkJw
    VGVGY3BLd3lLRjllU3owVVFtT2ROak9xZUNoOTZxSmlHOFliWU1nUDhSY2lWNTlvVwovOXpjR2h4
    cUU0dUdOWWtyaEFBQTRuVkpmNXE3L3RjQ0F3RUFBYU5UTUZFd0hRWURWUjBPQkJZRUZQRFNNV3NJ
    Ci9Eczd2VVpHdWJBRGdxUGNNMHdFTUI4R0ExVWRJd1FZTUJhQUZQRFNNV3NJL0RzN3ZVWkd1YkFE
    Z3FQY00wd0UKTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3RFFZSktvWklodmNOQVFFTEJRQURnZ0lC
    QUdBWHJNRUhVTDJiM2I3VApSb3NrYW12aW5ydytQa2h5c29qTGJWVzlsb3NaRlFZc1hWeG45M3Fq
    b1VtU3hIbElJOXVDem81Qkp3bzNjVGovCnN1aEJ2UndkSG85Mmp4YXp1ZXUvL3FWTGEvSmtkdnA4
    UDQydUdabGU3SGhjb2dlUTJhdDNhNXEyd0pRUXc1UWsKbTA2M3NqY1gveWRKdE9vY0V0YVYyUUow
    bHpQdEdNdHNCMk15eGJOMjBEQVJtYnBVeSt3bi9QQnhaWTRCOTVEaQpEcmFWNUMwK0ZCRGxtSzFq
    TDRwdlpJeXlmeHBJTitvTG9yc2xXb3RyYXhveHZQZHY5Z3NWMkJJQ2FlR05ldWM3CnFzK1UvUHBv
    d3pvVXh4WGJDRlZPUkkwbGRUSTBxUXFsU3JWczFLKzdiZktOTHplTkZMdWd3ME5qM3FRNzh0cHgK
    RnlhUUM3YVRibmZDc0RqbDJNYTIyVTZPM0FaclgyUTlaWG4weFdxSXF6QTROTTZPN3lQTzZLQTVM
    cTI2K0ZyNQpxWnlvMVhGV3hoUUJhRjJXRnFyQ3FsRlVUd2J6U0h3N2hXN21IL2lQdUR4WTZwZ1Zl
    d3VaalpSblc2QUNodU5sCkFtcjRRVGszWUZjRGwyY1J6Sk56bjltbzRxK0RjalRuZEd5ampYY0Fp
    Y2FMSEVWTXhZVzErVFJEdUgwa2JaczcKRGtXaGpPamREdW9PbHlxY0VuU0p0Z3Rqd0cxRDF2cHJZ
    MGhDdUNHSnlaa1djUk4zSEZIODlEekxSbXpoNzVwZgpGY0R1ckEyR2lRVlhIMUdlTWdXYmtPUXRv
    bXd5UjYwYlBseXB5SmNSalp1SWE3ZGo0cWxXcm05Y21WZGljVTl3CitNQUdYWDFFRjdmbkNhT0ZY
    TXFmK0JMVjQvL0cKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  localhost.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUpRZ0lCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQ1N3d2dna29BZ0VBQW9JQ0FRQ3d4NzFuN0Zzc01ORWMKcXJ2cXJ0U2U3anY5cW4yQ1JRMitD
    TExkRndGMjRGK20xWkJJZXlXUjExVi9GQlB2cTRSRjBwd1JTdGR5a2RCUQpnWDJISVBPT3d4bzI1
    eXpaNnJEbmg5ekUvK3NvL0xEQnJtMHcrcjhKT0NKWXNTRTQ0ZEo4QkFUS1ZhbjdEUlkrCnZZT0Jt
    bW1IOE9Lb2VyU1FOUUQwWW82WnkvWDA5NHdUMFAxYmZNaHRFd3lpMENqdHpzbUdKekdpZlI3NXho
    bksKS1d4UmNONTBOd3JDVjc4czJtd3BJUlB1KzBSNnZUelR3cWtFRWFqS1plZjdVcm1VV0pjLzN3
    OGlwQ3NzSzlwaQoyQkd0Qm5pVmJsQWo0ZWR2SHlOdXhzRzA0WTNEYi8zdUtzNUV5TEZ4Yy9xWUlI
    TXlDQlNmejAxeGxQMklKdC9uCi92VnVLUlNzRkR0WmVhenF5a3FnRUVndnpTNnIyQzNxd2ZjSmY4
    SlY2ZVVIRnRobjhNdVU0cTBqYlBKTjdCQWoKNmhmTUs5OWpYU095enVUK0lZWXlSd0J0NHBMcXdy
    eUlRN2ZWd3pqVHBYTDB3TmY5a2RFWU1MdEZtbFJDL3RUdAptRis3TE5hckJacUVsUVJSMmw5cW1P
    NDBhdkVuMHFBOWNKWWV2ejhJNUVTZEwrTmh1aTdtUTNnaW1URjBFMENXCnU1RlRPMjJFa29OSCs0
    U01QcVVoYk41cDlqSG04ZHUwK25DRWFwZE80blI0S1dyandkelNlNmYvNXZpaFNQdXkKOVJJUmVt
    R1hnc00wR2xONFZ5a3JESW9YMTVMUFJSQ1k1MDJNNnA0S0gzcW9tSWJ4aHRneUEveEZ5SlhuMmhi
    LwozTndhSEdvVGk0WTFpU3VFQUFEaWRVbC9tcnYrMXdJREFRQUJBb0lDQUEwUTltTDBDVmtlMHBY
    MzJLUGtBRHN2CkNLZ2JMZU92RHZENDI1K1R6N3Zsb2F4SEpMNzJ1elFvWWwxZU1vc0lkbUppeXI1
    TWRkZzJCdHVzZG9iQ1hMNDAKbFg5eFh0Tk1rWDdMZi9uZm9KWUs5MVdaZXVDZjUvYmFlMDlxNkRX
    NEcwS25XV05MS2FFd3VuQXd1Y09la2laRwpHN3F3TnlCaGlveUZyRnlad3JnMGc5b0RISGJpcGoz
    SnBxbHlFVlJpY0dyR0F0a3J2bHBmMWhBbk42WmRYVlBoCnJaM250bTJ1UjBoUzlaSTRhRHRhT1dD
    OWhwaVNaWk53TE5GYXIvVFRCM3JsRmMxTnJSTTZ1bzJMd3VLekU3NlgKeEx5aU9lVHd2RUczMXlG
    emVuTHptQ1UrYkxpUXpPekIwY2Zrdmg3NGtlMnQrTjlvVDhUOGVwZy9OQXpNWklhawpGWGVPdmJX
    NDc2Z3lUU1NQaUtlZWZLTFhNRVozbWlScWVyZk4wVXZ1U0syS2NJdjI4UUtLSUVQTGppL1Bmbm9W
    CllVR01KK2VHT3g1VWdBS1I5SERLSlN6bnVKNlZaYVpHaHpUK3lWQkFwbXM0Wnp2R0VjdVJoeTUw
    SFVNTmlyVHMKSlJ2elhEVU44Zko2TGpJZjlERWo4OFdqS3krc2M3d2t2ZnBWWTZNQy90TW9yVkZU
    QVlRb0oxNTJBRHFPeDFGWQpFamxBVGN1aVhsZGNFaVpjYnpSSDdSdlRjVmFDOGdPSW9iOW9Gc2xt
    ZWZmOFpqZDAwc3dWRmIwSkRMR1lkdWZICi96VStGRm1rYWxxNUlNWWE2a0I5d1FIQzJKWXRJb21j
    bXdFS1dIUzVuVTZqM016VW53MlV4NExBbkpHcVpMWGkKaWtMSWtNc24ycGNKQ3RUNTFZREJBb0lC
    QVFEVmw2TkNQS2dDWFNVNEd3eVBXQzBTWDIrbElyc1E0dUVLdUhIWQpQT2w5SWowUUZKQzN1U1JK
    TEJvZ1dwMDMxKzJpS21RekpTdkVNYVdKYUw1c1pyTXVFVnFoZzBHR1BUeUp3RVZuCmlIV0dqVFlu
    Z1UwTksxWldFb0JaQW5uT3BVTHdkejRESEcrcWxnSldDWEkvWVZha1FxWGptaEhYdlo0YkpiQWgK
    VUdvT1UxUDhpUThzUWh3RzRmL3I1dmRhR2hoZEZsdVB1aHRWaTh1UnpwODViTE0veU0zREhhUHpK
    WkJIRFc4eQpqRHBFSkRHcUhnUXVjYVQwT0o0T1ZDbXU1UlFhSkFQUmlDQ3g0Wk5jM05qRTBJcEFR
    K2IvZktTdUE0SGNFZjRkCllJZHBjYlNKUzBvNGNXUnpUWjJEYWF6dWxENXlxdzdGY1l5dDlTTVFt
    Rm5Hc3lsUEFvSUJBUURUNFFrU2xyWGEKQ09iRG1hVEtrQ1V2czhaZzhnYVFxZmoyRFBiaGlRS1lu
    NkRNL1VnY3dXODdLS1BucHdVNE1HTWlsN0x5V0VFOApBR0o3VFZMRU90Nm9iNTFxR3VEZVErZWor
    RUpmOUF4R0duVE9pa3EzSlFoalJzTG1ZYjBZK1VHclZTanpJNi9DCndtaXRac0FuYkQ2dEo1b2t1
    UmxsVVMvK0VhZ3M2VElXdWc2YW54QUdya2RDZ3dXNHNVNHhJbDlZaWp6VVJVUGYKNTVEclFtWDUv
    Z2VQVk44bmFGWDh6cUNwRTFJQ2w0M3hZMDQveFdTZnJNY1F6czdJTmFCK1RPK3pnbCtScEQrMwpx
    OWJydlZwY0dDQ29qVTFKL2F0RGlyNXRCVzg0RHYrc2FHRVhKMVBaN1FMaHd0c012d3J2V1JnbUtw
    RHlkNXBGCnNWUThOMzBaYzkvNUFvSUJBSE45Wm4wdUp2b0FPMXUyNUhldGlkRmhZUkM5VXNDeXJG
    UUxueUw0N0pjSXFGUEYKaXVxTVpSNWJobFR3S2dwRDZ1M0FWaVdCZDhUQncyd2xBckhDWmlnR29p
    YXF2Z2REblRRdWpsaUk1R000ZjR1awowbkRJZWdwWVBxWGlQTktMY1VKc2QwOWZWTkc4QXM5YWxE
    ZkkvZndiUFc5dm95NHdEUWxJdTQrSDE1Q2ZaYzRxCm5kV2tlVnNQWUQzQnlRVWpEd0ZtVVdQSmtY
    WVQvS0orUW9IZVVKMndpZkZ5V1cvalk3dkhlOVN0RmVRNlhkQksKSXFDcU9qTURXaE1OVnV5R1dQ
    UTVmUWNTdi9ydXFhdVFqblQ4L1lQNk16RDV5R0YrNi94K2poUjhXVHVlaTZ1ZwoxaVRteXhXOVpl
    bmtmZWtTcHlHQmRKODE0b2M5QVJTOEMrN3dlT2tDZ2dFQURhZnpiYjlJK1VTWm13SE1IVUl0Ckky
    WHk0MHkySDV6VTd3Ym00cUp5Q0dSQmVQVGFNUUJHcXdsemh2cTgyMkpEQVhmRmtOa2ZXejZyR2tk
    aGprUTkKRlo0Y0J6cTBRNThjenZTeFVuM29USnhuNnVmKzZNNzZPMnZVSkFVb3F2Tmx5Q1UwL25i
    T1hUOHFnQUtmWCtzYQpIdzd1WUcrTnMzb0lIZGdGZnQrSTJ1NGpBdFE5dERDSFowSUtuRnpSTFZt
    Snk2c2RRSkUyVHJnZUh3dW9odlJZCmlHUnYvWm83OEk5Z3k0VHpSRGVBYm81My9LUThXQTVLeGtx
    T0NWbHJmcmgydXBzc2piYUlaTTR1akFNb1Q4YysKVTU3SDNIejlETjFrYUtKeENLdnV6cTNybEJK
    MDFSYnhtSnQyZ3R2TldKL2xicEJQeDFEdUlJL05YaFExZSs1OApBUUtDQVFFQXdxTHlYWmJUNms0
    MFFFRDBLanZJdUNKUy9VdmxaaFg4b2ZZQnJQNFF2bEZRWEdaTE9FdllpZHN0CjQ1S2p1RGhCUFB5
    b2lKL1EzOEJKSHlWREdIWjExNTdTY2VOSWV1c3puSHM5eHJBTDRYVVZrQXhhSlp3WVFXZTIKZE9V
    Qm4zaEEwOHdRNDE3emV5dXVSNTg3Z1RMZUpYVkwwUHJGQzdab0syNXorc3FwSGgxQStPOFFjcjRT
    bnQ3Uwpsd2kvbGFCcE9jRTlMY0phSGJtMHRpZjc0OW9MWEZ5azFUUHpadGVQN1pvUmpqVk9yR2xK
    akdNcXA3ZEdTbU9VCnVGZ25EZTlaUGNoSU5aeGJaRThEQkZiRDNDclI2QUpYS2k0RFJPL2JNcnh6
    M3JQRlFrK2lrNW93aEtab0tRSmEKdVNjbXMxSGpLMEJZZUpTSDdQb1Uxa1VhMFNaS1JnPT0KLS0t
    LS1FTkQgUFJJVkFURSBLRVktLS0tLQo=