apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset
  labels:
    type: replica
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: replica-template
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: docker-pull-secret